### ISSUE TITLE
Domain is now a pornography site

### ISSUE THREAD

**Issue by nosmirck** [bibviz/bibviz#11]
At least, remove the url reference since it is really not a good thing to click the site to check the visualization and see something completely different.

**Comment by erasmuswill** [comment]
Also got burned by this one @danielgtaylor can I offer hosting+domain to continue this project? Otherwise, it can possibly be hosted on netlify or github pages?

**Comment by jlivingstonsg** [comment]
It is always here on internet library.
https://web.archive.org/web/20200223132234/http://bibviz.com/

**Comment by philb61** [comment]
Yeah, would have been great to know the domain was expiring and not being renewed.  I would have gladly bought it and re-hosted it, as I'm sure many would have.

**Comment by danielgtaylor** [comment]
Wow I'm super embarrassed about this, sorry everyone! It turns out I still own the domain, ran into a credit card issue with my server a few months ago and someone else was clever by re-using the DigitalOcean DNS servers but pointed it to their own server which redirects to a porn site. I changed the DNS, so within 24 hours it should no longer redirect there and instead will be a parking page.

@nosmirck @erasmuswill @jlivingstonsg @philb61 Is anybody willing to try and put this on GitHub pages? I can give anybody who wants it access. I unfortunately lost my server backups because they erase them after a few days of not paying due to the expired credit card. Would need to regenerate the site and throw it into a branch here, then I can set up a DNS CNAME to point here instead. Then it'll be safe for the future.

I'm juggling work, the pandemic, multiple young children some of which are in virtual school, other open source work, etc. Not trying to make excuses, just saying I don't have a ton of time for this at the moment :cry:

**Comment by philb61** [comment]
Is the data still safe?  Is it checked into this repo?  I have a Dreamhost account that gives me unlimited hosting, domains, etc...(on a shared server, of course.)  

If it is, I can try deploying it temporarily under one of my other domains so we can take a look and make sure everything works?  

Otherwise, I'm not sure how Github Pages work, but can look into it.  What could possibly go wrong ;-) ?

**Comment by jlivingstonsg** [comment]
I can get  this update to run and work on Gitpod.
https://github.com/idontusenumbers/bibviz

**Comment by jlivingstonsg** [comment]
Can someone try to set this version on GitHub pages?
https://github.com/idontusenumbers/bibviz

....

**Comment by philb61** [comment]
Done.

https://philb61.github.io/

**Comment by philb61** [comment]
FYI, lots of deprecation warnings on NPM install, including one that theoretically shouldn't work with Node 14, which is what I have.

`npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`
`npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`
`npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest`
`npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`
`npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated`
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated`
`npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`
`/usr/bin/wintersmith -> /usr/lib/node_modules/wintersmith/bin/wintersmith`
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/wintersmith/node_modules/chokidar/node_modules/fsevents):`
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

You can see what was built, etc, at https://github.com/philb61/philb61.github.io

**Comment by philb61** [comment]
I've changed the templates, etc, to generate https links, as I'm serving over https, and there were some hardcoded http links....

The one main issue may be addthis...

Uncaught ReferenceError: addthis is not defined
    <anonymous> https://philb61.github.io/:964

**Comment by philb61** [comment]
I've also updated a bunch of the npm packages and pushed that as well in my fork.

**Comment by jgrose** [comment]
Glad to hear you still have the domain! That was indeed a clever trick in hijacking DNS. @philb61 seems to have it setup but happy to help with any other issues. Thanks @philb61

**Comment by danielgtaylor** [comment]
@philb61 awesome! Thanks everyone. I've updated bibviz.com to do a simple redirect to https://philb61.github.io/ for now. Let me know if you want to set up a proper CNAME instead.

**Comment by philb61** [comment]
I'm also curious as to how they hijacked the DNS. They shouldn't be able to change the records in the registration if you still owned the domain.

Either way...I do have a dreamhost shared server I can put it on if you want it to look more "correct". That would just require me adding the hostname to my hosting, and you changing the registration to point to the dreamhost nameservers, I believe.

Once all the building is done, everything is self contained, correct?  I should be able to just pull my philb61.github.io repo anywhere, so that's easy (or anyone else can, or they can use my fork of the project to rebuild it anywhere.)

**Comment by jlivingstonsg** [comment]
Nice.
Bibviz work on GitHub pages now.

**Comment by philb61** [comment]
And I can confirm that it's self-contained. I pulled it under my host just to check, and so it would have Clourflare protection, etc...

So it's also at https://bibviz.philb.ca/

**Comment by jlivingstonsg** [comment]
There is a Youtube video that is not working.   Can you get another working link  and fix it?

**Comment by danielgtaylor** [comment]
@philb61 GitHub pages allows for CNAME records, e.g. check out https://rest.sh/ which uses it instead of https://danielgtaylor.github.io/restish. They will tell you to create a special record to prove you own the domain, and I can do that for you if you want to maintain the site on your GitHub account (or we can move it over to mine and I can give you and others access, either way is fine). We could also spin it off into an organization for better access control.

The DNS hack is interesting. My registrar isn't DigitalOcean, it's another company. I point that domain at the DO DNS servers (e.g. ns1.digitalocean.com, ns2.digitalocean.com, etc) so that I can configure the DNS stuff via DO since their interface is a million times better. My credit card expired, and DO's response is after one week to *delete everything* :angry: . So all my existing DNS stuff and my server were deleted, **but** (and here's the important part) it is still pointing to DO's name servers for resolution. Another user on DO must have noticed this and added the DNS A record (there is no verification process unless you dispute that someone owns the rights to the domain, which I'll be doing on the DO side shortly to get control back) and pointed it to their own virtual server which redirected to the porn site, presumably for money. Total scumbag move. My fix yesterday was to no longer point to ns1.digitalocean.com.

**Comment by philb61** [comment]
Ah.  Well, if Github pages allow a CNAME record that'll work properly, that may be the smarter way to go.

I don't plan on really doing much maintenance...but realistically, how much does it actually need?   It's probably smarter if you maintain ownership of it, but it's up to you.

And the fact that DO deletes the records and then allows anyone to add any A records for that domain without checking is...No further comment!

**Comment by jgrose** [comment]
I think an org would be ideal @danielgtaylor so I went ahead and made the bibviz org. Invited @philb61 & @danielgtaylor as admins and forked what philb61 into it. Please add anyone else if needed.

**Comment by danielgtaylor** [comment]
@jgrose I joined the org but it looks like I'm only a member, mind making me an admin? Once that's done I think I can make this repo redirect to the new organization instead and merge all the updates from @philb61's fork.

I did notice the individual pages don't render the lines anymore so that is broken. Same with the blog pages, and like mentioned above we probably want to replace the broken video. I can try to take some time later to take a peek and have it auto-publish on changes.

**Comment by jgrose** [comment]
Sorry @danielgtaylor it said your invite for the repo was still pending - but I went ahead and added you as an owner to the org, along with @philb61. I did 'invite' you to the repo as an admin and this time it seems you are good. If it was my mistake sorry - but things should be good now.

**Comment by philb61** [comment]
`I did notice the individual pages don't render the lines anymore so that is broken.`

Yeah, it looked odd to me, but I couldn't tell if they originally had lines. But like I had the working original to compare to!

You'll see when you attempt to build it that there are still errors. At least, there were when I did it, even after updating the dependencies I could. I'm not familiar with that particular build tool (nor with why the marked within it is a different version than the marked I updated to!), so I was flying pretty blindly unless I start reading a lot of docs. 

I just wanted to hopefully get it running so someone who knew what they were doing could take a look.

**Comment by jlivingstonsg** [comment]
If I paste in this Web adress
www.bibviz.com
to a Facebook comment it get blocked as porn.  Is there a way to make Facebook accept that webpage as Bibviz  again?

**Comment by jgrose** [comment]
> If I paste in this Web adress
> [www.bibviz.com](http://www.bibviz.com)
> to a Facebook comment it get blocked as porn. Is there a way to make Facebook accept that webpage as Bibviz again?

@jlivingstonsg As of today, it seems it's no longer being flagged. I've tested with my account. Would you, or someone else, confirm? Thank you!

**Comment by philb61** [comment]
> As of today, it seems it's no longer being flagged. I've tested with my account. Would you, or someone else, confirm? Thank you!

Worked for me when I shared it just now.

**Comment by jgrose** [comment]
> > As of today, it seems it's no longer being flagged. I've tested with my account. Would you, or someone else, confirm? Thank you!
> 
> Worked for me when I shared it just now.

Awesome. Will close this then as we've resolved the original issue (domain being forwarded to a porn site) which also resolved the facebook issue.
